title: Stackbit DIY Theme
baseURL: /
params:
  layout_type: full-width
  style: classic
  palette: gray
  mode: light
  base_font: serif
  header:
    title: DIY
    logo: images/icon.png
    logo_alt: DIY logo
    has_primary_nav: true
    primary_nav_links:
      - label: Features
        url: /features
        style: link
      - label: Pricing
        url: /pricing
        style: link
      - label: About
        url: /about
        style: link
      - label: Blog
        url: /blog
        style: link
      - label: Style Guide
        url: /style-guide
        style: link
    has_secondary_nav: true
    secondary_nav_links:
      - label: Contact
        url: /contact
        style: link
      - label: Get Started
        url: /pricing
        style: primary
    has_anncmnt: true
    anncmnt_content: >
      We use cookies to ensure that you get the best experience.<br>

      <p><a href="/"><span style="font-size: 12px;">Learn More<svg class="icon"
      viewBox="0 0 13 13" fill="#fff" width="100%"><path d="M11.114
      5.245l-.132.297a2 2 0 01-.414.602l-6.455 6.455-.707-.707 6.455-6.455a2 2 0
      01.602-.414l.297-.132-.7.076H5.881v-1h6.157v6.157h-1V5.98l.076-.736z"></path></svg></span></a></p>
    anncmnt_align: left
    anncmnt_is_home_only: true
    anncmnt_has_close: true
    anncmnt_id: new-features
  footer:
    logo: 
    logo_alt: 
    has_primary_nav: true
    primary_nav_title: Company
    primary_nav_links:
      - label: About
        url: /about
        style: link
      - label: Style Guide
        url: /style-guide
        style: link
    has_secondary_nav: true
    secondary_nav_title: Blog
    secondary_nav_links:
      - label: News
        url: /blog/category/news
        style: link
      - label: General
        url: /blog/category/general
        style: link
      - label: Tutorials
        url: /blog/category/tutorials
        style: link
    has_tertiary_nav: true
    tertiary_nav_title: Legal
    tertiary_nav_links:
      - label: Terms & Conditions
        url: /terms-conditions
        style: link
      - label: Privacy Policy
        url: /privacy-policy
        style: link
    has_social: true
    social_links:
      - label: Facebook
        url: 'https://facebook.com/'
        style: link
        has_icon: true
        icon: facebook
        icon_position: center
        new_window: true
      - label: Instagram
        url: 'https://instagram.com/rarehashorg'
        style: link
        has_icon: true
        icon: instagram
        icon_position: center
        new_window: true
      - label: Twitter
        url: 'https://twitter.com/rarehash'
        style: link
        has_icon: true
        icon: twitter
        icon_position: center
        new_window: true
      - label: GitHub
        url: 'https://github.com/rarehash'
        style: link
        has_icon: true
        icon: github
        icon_position: center
        new_window: true
      - label: LinkedIn
        url: 'https://xn.linkedin.com/company/rarehash'
        style: link
        has_icon: true
        icon: linkedin
        icon_position: center
        new_window: true
    content: Rarehash. All rights reserved.
  domain: 'https://website-template-93ff3.netlify.app'
  favicon: images/favicon.png
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
